from flask import Flask, render_template, request, jsonify, redirect, url_for
from model_utils import SystemBackend
from PIL import Image
import numpy as np
from datetime import datetime
from fpdf import FPDF
import os

app = Flask(__name__)
backend = SystemBackend()

if not os.path.exists('static'):
    os.makedirs('static')

LAST_IMAGE_PATH = os.path.join("static", "temp_xray.jpg")

@app.route('/')
def login():
    return render_template('login.html')

@app.route('/dashboard')
def dashboard():
    return render_template('index.html')

@app.route('/analyze', methods=['POST'])
def analyze():
    if 'file' not in request.files:
        return jsonify({'error': 'No file uploaded'}), 400
    
    file = request.files['file']
    if file.filename == '':
        return jsonify({'error': 'No selected file'}), 400
        
    try:
        img = Image.open(file.stream).convert('RGB')
        img.save(LAST_IMAGE_PATH) 
        
        img_np = np.array(img)
        variance, is_blurry = backend.check_blur(img_np)
        label, confidence = backend.predict(img)
        
        response_data = {
            'label': str(label),
            'confidence': f"{float(confidence):.2f}",
            'sharpness': f"{float(variance):.1f}",
            'is_blurry': bool(is_blurry),
            'timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }
        return jsonify(response_data)

    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/report', methods=['POST'])
def generate_report():
    data = request.json
    patient_name = data.get('patient_name', f"ANON-{np.random.randint(1000,9999)}")

    pdf = FPDF()
    pdf.add_page()
    
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="Multimodal Pneumonia Detection Report", ln=True, align='C')
    
    pdf.set_font("Arial", size=12)
    pdf.ln(10)
    pdf.cell(200, 10, txt=f"Date: {datetime.now().strftime('%Y-%m-%d')}", ln=True)
    pdf.cell(200, 10, txt=f"Patient: {patient_name}", ln=True)
    
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="Diagnostic Analysis", ln=True)
    
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Prediction: {data['label']}", ln=True)
    pdf.cell(200, 10, txt=f"Confidence: {data['confidence']}%", ln=True)
    pdf.cell(200, 10, txt=f"Image Quality: {data['sharpness']}", ln=True)
    
    pdf.ln(10)
    if os.path.exists(LAST_IMAGE_PATH):
        x_pos = (210 - 100) / 2
        pdf.image(LAST_IMAGE_PATH, x=x_pos, w=100)
    
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 10)
    pdf.multi_cell(0, 10, "Disclaimer: This report is generated by an AI decision-support system (ResNet50+CLIP). It is not a definitive medical diagnosis. Please consult a radiologist.")
    
    report_filename = f"report_{np.random.randint(1000,9999)}.pdf"
    report_path = os.path.join("static", report_filename)
    pdf.output(report_path)
    
    return jsonify({'url': report_path})

if __name__ == '__main__':
    app.run(debug=True, port=5000)